In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [2]:
df = pd.read_csv('train.txt',sep=';',header = None,names = ['text','emotion'])

In [3]:
df.head()

                                                text  emotion
0                            i didnt feel humiliated  sadness
1  i can go from feeling so hopeless to so damned...  sadness
2   im grabbing a minute to post i feel greedy wrong    anger
3  i am ever feeling nostalgic about the fireplac...     love
4                               i am feeling grouchy    anger

In [4]:
df.isnull().sum()

text       0
emotion    0
dtype: int64

In [5]:
unique_emotion = df['emotion'].unique()
unique_emotion

array(['sadness', 'anger', 'love', 'surprise', 'fear', 'joy'],
      dtype=object)

In [6]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
df['emotion'] = le.fit_transform(df['emotion'])

In [7]:
df['emotion'].unique()

array([4, 0, 3, 5, 1, 2])

In [8]:
df['text'] = df['text'].apply(lambda x: x.lower())

In [9]:
import string 
def remove_punc(txt):
    return txt.translate(str.maketrans('','',string.punctuation))
df['text'] = df['text'].apply(remove_punc)

In [10]:
def remove_numbers(txt):
    new = ""
    for i in txt:
        if not i.isdigit():
            new = new + i
    return new

df['text'] = df['text'].apply(remove_numbers)

In [11]:
def remove_emojis(txt):
    new = ""
    for i in txt:
        if i.isascii():
            new += i
    return new

df['text'] = df['text'].apply(remove_emojis)

In [12]:
from nltk.corpus import stopwords
from nltk.tokenize import word_tokenize

In [13]:
import nltk
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt is already up-to-date!
[nltk_data] Downloading package stopwords to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package stopwords is already up-to-date!
[nltk_data] Downloading package punkt_tab to
[nltk_data]     C:\Users\DELL\AppData\Roaming\nltk_data...
[nltk_data]   Package punkt_tab is already up-to-date!

True

In [14]:
stop_words = set(stopwords.words('english'))
len(stop_words)

198

In [15]:
type(stop_words)

set

In [16]:
def remove(txt):
    words = word_tokenize(txt)
    cleaned = []
    for i in words:
        if i not in stop_words: 
            cleaned.append(i)
    return ' '.join(cleaned)

df['text'] = df['text'].apply(remove)

In [17]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        4
1  go feeling hopeless damned hopeful around some...        4
2          im grabbing minute post feel greedy wrong        0
3  ever feeling nostalgic fireplace know still pr...        3
4                                    feeling grouchy        0

In [18]:
from sklearn.model_selection import train_test_split
X_train,X_test,y_train,y_test = train_test_split(df['text'],df['emotion'],random_state=42,test_size=0.20)

In [19]:
X_train.shape

(12800,)

In [20]:
X_test.shape

(3200,)

In [21]:
from sklearn.feature_extraction.text import TfidfVectorizer,CountVectorizer

In [22]:
bow_vectorizer = CountVectorizer()

In [23]:
X_train_bow = bow_vectorizer.fit_transform(X_train)
X_test_bow = bow_vectorizer.transform(X_test)

In [24]:
from sklearn.naive_bayes import MultinomialNB
from sklearn.metrics import accuracy_score

In [25]:
nb = MultinomialNB()

In [26]:
nb.fit(X_train_bow,y_train)

MultinomialNB()

In [27]:
y_pred = nb.predict(X_test_bow)

In [28]:
accuracy = accuracy_score(y_test,y_pred)
accuracy

0.7678125

# uSING tFIDF_vECTORIZER

In [29]:
tfidf_vec =TfidfVectorizer()

In [30]:
X_train,X_test,y_train,y_test = train_test_split(df['text'],df['emotion'],random_state=42,test_size=0.20)

In [31]:
X_train_tf = tfidf_vec.fit_transform(X_train)
X_test_tf = tfidf_vec.transform(X_test)

In [32]:
nb1 = MultinomialNB()
nb1.fit(X_train_tf,y_train)

MultinomialNB()

In [33]:
y_pred_tfidf = nb1.predict(X_test_tf)

In [34]:
accuracy1 = accuracy_score(y_test,y_pred_tfidf)
accuracy1

0.6609375

# Let's implement the same using Logistic Regression

In [35]:
from sklearn.linear_model import LogisticRegression

In [36]:
logistic = LogisticRegression()

In [37]:
logistic.fit(X_train_tf,y_train)

LogisticRegression()

In [38]:
y_pred = logistic.predict(X_test_tf)

In [39]:
accuracy2 = accuracy_score(y_test,y_pred)
accuracy2

0.8615625

In [40]:
pip install textblob

Requirement already satisfied: textblob in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (0.19.0)
Requirement already satisfied: nltk>=3.9 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from textblob) (3.9.3)
Requirement already satisfied: click in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from nltk>=3.9->textblob) (8.2.1)
Requirement already satisfied: joblib in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from nltk>=3.9->textblob) (1.5.1)
Requirement already satisfied: regex>=2021.8.3 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from nltk>=3.9->textblob) (2025.11.3)
Requirement already satisfied: tqdm in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from nltk>=3.9->textblob) (4.67.1)
Requirement already satisfied: colorama in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from click->nltk>=3.9->textblob) (0.4.6)
Note: you may need to restart the kernel to use updated packages.

In [41]:
Ksh = '😁😁😁😁'
Ksh.encode('utf-8')

b'\xf0\x9f\x98\x81\xf0\x9f\x98\x81\xf0\x9f\x98\x81\xf0\x9f\x98\x81'

In [42]:
from textblob import TextBlob
incorrect_txt = "i am a booy"
TextBlob(incorrect_txt).correct()

TextBlob("i am a body")

In [43]:
from nltk.tokenize import sent_tokenize,word_tokenize

In [44]:
sent = "Lorem Ipsum is simply dummy text of the printing and typesetting industry. Lorem Ipsum has been the industry standard dummy text ever since the 1500s, when an unknown printer took a galley of type and scrambled it to make a type specimen book. It has survived not only five centuries, but also the leap into electronic typesetting, remaining essentially unchanged. It was popularised in the 1960s with the release of Letraset sheets containing Lorem Ipsum passages, and more recently with desktop publishing software like Aldus PageMaker including versions of Lorem Ipsum."
sents = sent_tokenize(sent)
# type(sents)
words = word_tokenize(sent)
words

['Lorem',
 'Ipsum',
 'is',
 'simply',
 'dummy',
 'text',
 'of',
 'the',
 'printing',
 'and',
 'typesetting',
 'industry',
 '.',
 'Lorem',
 'Ipsum',
 'has',
 'been',
 'the',
 'industry',
 'standard',
 'dummy',
 'text',
 'ever',
 'since',
 'the',
 '1500s',
 ',',
 'when',
 'an',
 'unknown',
 'printer',
 'took',
 'a',
 'galley',
 'of',
 'type',
 'and',
 'scrambled',
 'it',
 'to',
 'make',
 'a',
 'type',
 'specimen',
 'book',
 '.',
 'It',
 'has',
 'survived',
 'not',
 'only',
 'five',
 'centuries',
 ',',
 'but',
 'also',
 'the',
 'leap',
 'into',
 'electronic',
 'typesetting',
 ',',
 'remaining',
 'essentially',
 'unchanged',
 '.',
 'It',
 'was',
 'popularised',
 'in',
 'the',
 '1960s',
 'with',
 'the',
 'release',
 'of',
 'Letraset',
 'sheets',
 'containing',
 'Lorem',
 'Ipsum',
 'passages',
 ',',
 'and',
 'more',
 'recently',
 'with',
 'desktop',
 'publishing',
 'software',
 'like',
 'Aldus',
 'PageMaker',
 'including',
 'versions',
 'of',
 'Lorem',
 'Ipsum',
 '.']

In [45]:
df.head()

                                                text  emotion
0                              didnt feel humiliated        4
1  go feeling hopeless damned hopeful around some...        4
2          im grabbing minute post feel greedy wrong        0
3  ever feeling nostalgic fireplace know still pr...        3
4                                    feeling grouchy        0

In [46]:
df['text'].str.upper()

0                                    DIDNT FEEL HUMILIATED
1        GO FEELING HOPELESS DAMNED HOPEFUL AROUND SOME...
2                IM GRABBING MINUTE POST FEEL GREEDY WRONG
3        EVER FEELING NOSTALGIC FIREPLACE KNOW STILL PR...
4                                          FEELING GROUCHY
                               ...
15995        BRIEF TIME BEANBAG SAID ANNA FEEL LIKE BEATEN
15996    TURNING FEEL PATHETIC STILL WAITING TABLES SUB...
15997                             FEEL STRONG GOOD OVERALL
15998                       FEEL LIKE RUDE COMMENT IM GLAD
15999                         KNOW LOT FEEL STUPID PORTRAY
Name: text, Length: 16000, dtype: object

In [47]:
pip install spacy

Requirement already satisfied: spacy in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (3.7.5)
Requirement already satisfied: spacy-legacy<3.1.0,>=3.0.11 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: spacy-loggers<2.0.0,>=1.0.0 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (1.0.5)
Requirement already satisfied: murmurhash<1.1.0,>=0.28.0 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (1.0.15)
Requirement already satisfied: cymem<2.1.0,>=2.0.2 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (2.0.13)
Requirement already satisfied: preshed<3.1.0,>=3.0.2 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (3.0.12)
Requirement already satisfied: thinc<8.3.0,>=8.2.2 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (8.2.5)
Requirement already satisfied: wasabi<1.2.0,>=0.9.1 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (1.1.3)
Requirement already satisfied: srsly<3.0.0,>=2.4.3 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (2.5.2)
Requirement already satisfied: catalogue<2.1.0,>=2.0.6 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (2.0.10)
Requirement already satisfied: weasel<0.5.0,>=0.1.0 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (0.4.3)
Requirement already satisfied: typer<1.0.0,>=0.3.0 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (0.24.1)
Requirement already satisfied: tqdm<5.0.0,>=4.38.0 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (4.67.1)
Requirement already satisfied: requests<3.0.0,>=2.13.0 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (2.32.3)
Requirement already satisfied: pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (2.12.5)
Requirement already satisfied: jinja2 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (3.1.6)
Requirement already satisfied: setuptools in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (72.1.0)
Requirement already satisfied: packaging>=20.0 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (24.2)
Requirement already satisfied: langcodes<4.0.0,>=3.2.0 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (3.5.1)
Requirement already satisfied: numpy>=1.19.0 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from spacy) (1.26.4)
Requirement already satisfied: annotated-types>=0.6.0 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.7.0)
Requirement already satisfied: pydantic-core==2.41.5 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (2.41.5)
Requirement already satisfied: typing-extensions>=4.14.1 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (4.14.1)
Requirement already satisfied: typing-inspection>=0.4.2 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from pydantic!=1.8,!=1.8.1,<3.0.0,>=1.7.4->spacy) (0.4.2)
Requirement already satisfied: charset-normalizer<4,>=2 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.3.2)
Requirement already satisfied: idna<4,>=2.5 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (3.7)
Requirement already satisfied: urllib3<3,>=1.21.1 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2.5.0)
Requirement already satisfied: certifi>=2017.4.17 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from requests<3.0.0,>=2.13.0->spacy) (2026.1.4)
Requirement already satisfied: blis<0.8.0,>=0.7.8 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from thinc<8.3.0,>=8.2.2->spacy) (0.7.11)
Requirement already satisfied: confection<1.0.0,>=0.0.1 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from thinc<8.3.0,>=8.2.2->spacy) (0.1.5)
Requirement already satisfied: colorama in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from tqdm<5.0.0,>=4.38.0->spacy) (0.4.6)
Requirement already satisfied: click>=8.2.1 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (8.2.1)
Requirement already satisfied: shellingham>=1.3.0 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (1.5.4)
Requirement already satisfied: rich>=12.3.0 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (14.3.3)
Requirement already satisfied: annotated-doc>=0.0.2 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from typer<1.0.0,>=0.3.0->spacy) (0.0.4)
Requirement already satisfied: typer-slim<1.0.0,>=0.3.0 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.24.0)
Requirement already satisfied: cloudpathlib<1.0.0,>=0.7.0 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (0.23.0)
Requirement already satisfied: smart-open<8.0.0,>=5.2.1 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from weasel<0.5.0,>=0.1.0->spacy) (7.5.1)
Requirement already satisfied: wrapt in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from smart-open<8.0.0,>=5.2.1->weasel<0.5.0,>=0.1.0->spacy) (2.1.2)
Requirement already satisfied: markdown-it-py>=2.2.0 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (4.0.0)
Requirement already satisfied: pygments<3.0.0,>=2.13.0 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (2.19.1)
Requirement already satisfied: mdurl~=0.1 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from markdown-it-py>=2.2.0->rich>=12.3.0->typer<1.0.0,>=0.3.0->spacy) (0.1.2)
Requirement already satisfied: MarkupSafe>=2.0 in c:\users\dell\anaconda3\envs\myenv\lib\site-packages (from jinja2->spacy) (3.0.2)
Note: you may need to restart the kernel to use updated packages.

In [49]:
import spacy
nlp = spacy.load('en_core_web_sm')

In [50]:
sent5 = 'I have a Ph.D in A.I'
sent6 = "We're here to help! mail us at nks@gmail.com"
sent7 = 'A 5km ride cost $10.50'
sent1 = 'I am going to visit delhi!'

In [51]:
doc1 = nlp(sent5)
doc2 = nlp(sent6)
doc3 = nlp(sent7)
doc4 = nlp(sent1)

In [57]:
for token in [doc1,doc2,doc3,doc4]:
    for toke in token:
        print(toke)
    print("\n")

I
have
a
Ph
.
D
in
A.I


We
're
here
to
help
!
mail
us
at
nks@gmail.com


A
5
km
ride
cost
$
10.50


I
am
going
to
visit
delhi
!

In [58]:
from nltk.stem.porter import PorterStemmer
ps = PorterStemmer()

In [61]:
def stem_words(text):
    return " ".join([ps.stem(word) for word in text.split()])

In [62]:
sample = 'walk walking walked'
stem_words(sample)

'walk walk walk'

In [72]:
import nltk
from nltk.stem import WordNetLemmatizer
wordnet_lemmatizer = WordNetLemmatizer()

sentence = "He was running and eating at same time. He has bad habit of swimming after playing long hours in the Sun."
punctuations="?:!.,;"
sentence_words = nltk.word_tokenize(sentence)
for word in sentence_words:
     if word in punctuations:
         sentence_words.remove(word)

sentence_words
print("{0:20}{1:20}".format("Word","Lemma"))
for word in sentence_words:
    print ("{0:20}{1:20}".format(word,wordnet_lemmatizer.lemmatize(word,pos='v')))

Word                Lemma
He                  He
was                 be
running             run
and                 and
eating              eat
at                  at
same                same
time                time
He                  He
has                 have
bad                 bad
habit               habit
of                  of
swimming            swim
after               after
playing             play
long                long
hours               hours
in                  in
the                 the
Sun                 Sun

In [73]:
import numpy as np

def outlier(x):
    # x = np.array(x, dtype=int)

    Q1 = np.percentile(x, 25)
    Q3 = np.percentile(x, 75)

    IQR = Q3 - Q1

    lower = Q1 - 1.5 * IQR
    upper = Q3 + 1.5 * IQR

    outliers = [v for v in x if (v < lower) or (v > upper)]
    
    if len(outliers) > 0:
        # print(" ".join(map(str, outliers)))
        print(*outliers)

In [77]:
x = [10 ,10, 6, 9, 4, 5, 7, 1, 8, 929, 100]
x=[1,1,2]
outlier(x)